# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team11_p1', models.CharField(max_length=200)),
                ('team11_p2', models.CharField(max_length=200)),
                ('team11_s', models.CharField(max_length=200)),
                ('team12_p1', models.CharField(max_length=200)),
                ('team12_p2', models.CharField(max_length=200)),
                ('team12_s', models.CharField(max_length=200)),
            ],
        ),
    ]
