# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190401_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='team2_score',
            field=models.CharField(max_length=200),
        ),
    ]
